fabiand/traviskube

.travis.yml
ci/deploy-kubevirt
ci/prepare-host
test.sh

Small fixes

---

.travis.yml
ci/prepare-host

Allow installing virtctl

---

ci/prepare-host

Permit installing oc only

---

ci/prepare-host
ci/start-cluster

Fix minikube var retrieval

---

.travis.yml

ci: Use jobs

---

.travis.yml

Deploy KubeVirt v0.9.1

---

ci/prepare-host
test.sh

minikube: Update to v0.30.0

---

.travis.yml
README.md
ci/defaults
ci/deploy-kubevirt
ci/prepare-host
ci/start-cluster
ci/wait-pods-ok
ci/workaround

Previously platform, distribution, and versions had to be specified.
Now sane defaults will be selected if nothing was specified.

Set sane defaults and fixes

---

ci/deploy-kubevirt
ci/prepare-host
ci/start-cluster

Better way to source defaults

---

ci/defaults

KubeVirt v0.10.0

---

.travis.yml
ci/defaults

kubevirt: Update to v0.11.0

---

ci/prepare-host

minikube: Update to v0.33.1

---

ci/defaults

kubevirt: Update to v0.14.0

---

.travis.yml
ci/deploy-kubevirt

kubevirt: Switch deployment to use the operator

---

ci/defaults

Update to kubevirt v0.17.0

---

ci/deploy-kubevirt

deploy: Drop SCC creation

---

.travis.yml
ci/prepare-host

- minikube to v1.0.1
- kubectl to v1.14.0
- crictl to v1.14.0

Update minikube, kubectl, and crictl

---

ci/defaults

Update kubevirt to v0.18.1

---

.travis.yml
ci/defaults
ci/prepare-host
ci/start-cluster

https://github.com/kubernetes-sigs/kind/

Add support for kind

---

ci/defaults

Update to kubevirt-v0.19.0

---

ci/defaults
ci/deploy-kubevirt
test.sh

Update to kubevirt-v0.22.0

---

ci/prepare-host

kind: Update to v0.5.1

---

ci/defaults

Update to kubevirt v0.23.0

---

ci/prepare-host

Use latest minikube for testing

Use latest minikube

---

ci/defaults

kubevirt: Update to v0.26.0

---

.travis.yml
ci/defaults

Update to kubevirt-v0.27.0

---

ci/defaults

Update to kubevirt-v0.28.0

---

.travis.yml
ci/defaults
ci/prepare-host
ci/start-cluster

Introduce support for testing with k3s

Support k3s

---

ci/prepare-host

Update crictl and kubectl

---

ci/defaults

kubevirt: Update to v0.33.0

---

ci/prepare-host
ci/start-cluster

kind: Update to v0.9.0
